# Generated by Django 6.0 on 2025-12-12 07:39

import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapeuticUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('emotional_profile', models.CharField(choices=[('avoidant', 'Tend to avoid challenges'), ('anxious', 'Experience learning anxiety'), ('doubtful', 'Struggle with self-doubt'), ('overwhelmed', 'Easily overwhelmed'), ('balanced', 'Fairly balanced'), ('resilient', 'Building resilience')], db_index=True, default='balanced', max_length=20)),
                ('learning_style', models.CharField(blank=True, choices=[('visual', 'Visual learner'), ('auditory', 'Auditory learner'), ('kinesthetic', 'Hands-on learner'), ('reading', 'Reading/writing learner')], default='visual', max_length=20, null=True)),
                ('daily_time_limit', models.PositiveIntegerField(default=30, help_text='Maximum recommended learning minutes per day', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)])),
                ('preferred_learning_hours', models.JSONField(blank=True, default=list, help_text='List of preferred hours for learning (0-23)')),
                ('gentle_mode', models.BooleanField(db_index=True, default=True)),
                ('hide_progress', models.BooleanField(default=True)),
                ('allow_anonymous', models.BooleanField(default=True)),
                ('receive_gentle_reminders', models.BooleanField(default=True)),
                ('current_stress_level', models.IntegerField(db_index=True, default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('total_learning_minutes', models.PositiveIntegerField(default=0)),
                ('consecutive_days', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('therapy_start_date', models.DateField(auto_now_add=True)),
                ('breakthrough_moments', models.JSONField(blank=True, default=list, help_text='List of dates and descriptions of breakthrough moments')),
                ('avatar_color', models.CharField(default='#3498db', max_length=7)),
                ('custom_affirmation', models.CharField(blank=True, max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Therapeutic User',
                'verbose_name_plural': 'Therapeutic Users',
                'db_table': 'therapeutic_users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['emotional_profile', 'gentle_mode'], name='therapeutic_emotion_c3d5d9_idx'), models.Index(fields=['current_stress_level'], name='therapeutic_current_631170_idx')],
            },
        ),
    ]
