# Generated by Django 6.0 on 2026-05-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_therapeuticuser_account_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapeuticuser',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='If set, the account is locked until this timestamp for therapeutic reasons', null=True),
        ),
    ]
