"""
Django settings for therapeutic_coding project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load sensitive settings from environment when available. Defaults preserve
# current development values so this change is non-breaking; override in
# production via environment variables and refrain from committing secrets.
_FILE_SECRET_KEY = 'django-insecure-t3&mx#pn050!0s3^9jl60@_zlz&x8968y=y6k1uuqy&-9lxu+#'
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', _FILE_SECRET_KEY)

# Preserve existing default but allow overriding with DJANGO_DEBUG
_FILE_DEBUG = True
DEBUG = os.getenv('DJANGO_DEBUG', str(_FILE_DEBUG)) == 'True'

# Allow configuring allowed hosts via environment; in production set DJANGO_ALLOWED_HOSTS
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS')
if ALLOWED_HOSTS:
    ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django_extensions',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',                    # Django REST Framework
    'django_filters',                    # Django Filters
    'corsheaders',                       # CORS for frontend
    'crispy_forms',
    'crispy_bootstrap5',
    'channels',
    'rest_framework_simplejwt.token_blacklist',
    
    # Your apps (without apps. prefix since we added apps to path)
    'users',
    'therapy',
    'learning',
    'social',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise (optional) to serve static files in simple deployments
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CORS should be high in the chain so it can add headers before responses are finalized
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    



    #'users.middleware.TherapeuticMiddleware',
    #'users.middleware.StressAwareMiddleware',
    #'users.middleware.GentleResponseMiddleware',
]

ROOT_URLCONF = 'therapeutic_coding.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',
            # Add these to match therapy/users pattern:
            BASE_DIR / 'therapy' / 'templates',
            BASE_DIR / 'users' / 'templates',
            BASE_DIR / 'social' / 'templates',  # Add this line
            BASE_DIR / 'learning' / 'templates',
            BASE_DIR / 'chat' / 'templates',],  # Add this line

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],  
        },
    },
]

WSGI_APPLICATION = 'therapeutic_coding.wsgi.application'

# ASGI app for Channels (will fall back to WSGI if Channels not used)
ASGI_APPLICATION = os.getenv('DJANGO_ASGI_APPLICATION', 'therapeutic_coding.asgi.application')


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
# Static files configuration


# # Static files (CSS, JavaScript, Images)
# STATIC_URL = 'static/'

# STATICFILES_DIRS = [
#     BASE_DIR / "static",
#     BASE_DIR / "therapy/static",
#     BASE_DIR / "users/static",
#     BASE_DIR / "learning/static",   
#     BASE_DIR / "social/static",
#     BASE_DIR / "chat/static",

# ]

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

# Production-ready static configuration (collectstatic -> STATIC_ROOT). In
# development these defaults preserve current behavior. Consider using a CDN
# or S3-backed storage in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Use WhiteNoise's compressed manifest storage in production to ensure
# files are served efficiently and with long cache lifetimes.
STATICFILES_STORAGE = os.getenv(
    'DJANGO_STATICFILES_STORAGE',
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Remove or comment out these duplicate lines:
# STATICFILES_DIRS = [BASE_DIR / 'static']  # DELETE THIS LINE
# STATIC_ROOT = BASE_DIR / 'staticfiles'    # DELETE THIS LINE (already defined above)
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Custom user model
#AUTH_USER_MODEL = 'users.User'

# Login/Logout URLs
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'therapy:dashboard'
LOGOUT_REDIRECT_URL = 'home'


# Add REST Framework configuration
REST_FRAMEWORK = {
    # Prefer JWT in production; keep SessionAuthentication as a fallback for
    # browser-based interactions. Install djangorestframework-simplejwt and
    # configure token lifetimes in env for production use.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': int(os.getenv('DJANGO_PAGE_SIZE', '10')),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# DRF throttling (conservative defaults)
REST_FRAMEWORK.setdefault('DEFAULT_THROTTLE_CLASSES', [
    'rest_framework.throttling.AnonRateThrottle',
    'rest_framework.throttling.UserRateThrottle',
])
REST_FRAMEWORK.setdefault('DEFAULT_THROTTLE_RATES', {
    'anon': os.getenv('DRF_ANON_RATE', '10/min'),
    'user': os.getenv('DRF_USER_RATE', '60/min'),
    'presence': os.getenv('DRF_PRESENCE_RATE', '30/min'),
})

# Add these at the bottom
AUTH_USER_MODEL = 'users.TherapeuticUser'  # CRITICAL

# Simple JWT configuration (env-driven; install djangorestframework-simplejwt)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MINUTES', '60'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': os.getenv('JWT_ALGORITHM', 'HS256'),
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# CORS Settings (for frontend)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# ----------------------
# Redis / Cache Settings
# ----------------------
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')
REDIS_KEY_PREFIX = os.getenv('REDIS_KEY_PREFIX', 'cs:')

# Configure Django cache to use Redis via django-redis
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # Fail gracefully: ignore exceptions so site stays up if Redis is down
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': REDIS_KEY_PREFIX,
    }
}

# Short default cache TTL for presence keys (seconds)
PRESENCE_TTL = int(os.getenv('PRESENCE_TTL', '45'))

# Channels (Redis channel layer)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        }
    }
}

# Health-check settings for Redis
REDIS_HEALTHCHECK_TIMEOUT = int(os.getenv('REDIS_HEALTHCHECK_TIMEOUT', '2'))


# Basic structured logging config - expand in production to ship to log aggregator
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
    },
}

# Login/Logout URLs.py
LOGIN_URL = '/login/'  # Should be this, not '/users/login/'
LOGIN_REDIRECT_URL = '/therapy/'  # Or wherever you want users to go after login
LOGOUT_REDIRECT_URL = '/login/'  # Where to go after logout

# Email backend (for password reset)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Add authentication backends
AUTHENTICATION_BACKENDS = [
    'users.authentication.TherapeuticAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',  # Keep default
]