# Generated by Django 6.0 on 2025-12-12 07:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField()),
                ('difficulty_level', models.IntegerField(choices=[(1, '🌱 Gentle Introduction'), (2, '🌿 Building Confidence'), (3, '🌳 Comfort Zone +1'), (4, '🏔️ Gentle Challenge'), (5, '🚀 Mastery Track')], default=1)),
                ('target_language', models.CharField(choices=[('python', 'Python'), ('web', 'HTML/CSS/JS'), ('django', 'Django'), ('mixed', 'Mixed Technologies')], max_length=20)),
                ('recommended_for_profiles', models.JSONField(default=list, help_text='Emotional profiles this path is recommended for')),
                ('estimated_total_hours', models.PositiveIntegerField(default=10)),
                ('max_daily_minutes', models.PositiveIntegerField(default=30)),
                ('modules', models.JSONField(default=list, help_text='List of module IDs in order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Learning Paths',
                'ordering': ['difficulty_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MicroActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField()),
                ('activity_type', models.CharField(choices=[('concept', 'Concept Introduction'), ('practice', 'Practice Exercise'), ('project', 'Mini Project'), ('review', 'Review/Reflection'), ('challenge', 'Gentle Challenge'), ('gamified', 'Gamified Learning')], default='practice', max_length=20)),
                ('therapeutic_focus', models.CharField(choices=[('confidence', 'Building Confidence'), ('patience', 'Developing Patience'), ('resilience', 'Building Resilience'), ('focus', 'Improving Focus'), ('creativity', 'Encouraging Creativity'), ('mindfulness', 'Mindful Coding')], default='confidence', max_length=20)),
                ('difficulty_level', models.IntegerField(db_index=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('primary_language', models.CharField(max_length=20)),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='List of technologies used')),
                ('estimated_minutes', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('no_time_limit', models.BooleanField(default=True)),
                ('infinite_retries', models.BooleanField(default=True)),
                ('skip_allowed', models.BooleanField(default=True)),
                ('gentle_feedback', models.BooleanField(default=True)),
                ('learning_objectives', models.JSONField(default=list, help_text='List of learning objectives')),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='List of prerequisite activity IDs')),
                ('starter_code', models.TextField(blank=True)),
                ('solution_code', models.TextField(blank=True)),
                ('test_cases', models.JSONField(blank=True, default=list, help_text='Test cases for automatic validation')),
                ('validation_type', models.CharField(choices=[('completion', 'Completion is success'), ('output_match', 'Output must match'), ('test_passing', 'Tests must pass'), ('code_review', 'Code review required'), ('self_assessment', 'Self-assessment only')], default='completion', max_length=20)),
                ('video_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('additional_resources', models.JSONField(blank=True, default=list, help_text='List of additional resource URLs')),
                ('therapeutic_instructions', models.JSONField(default=list, help_text='Pre- and post-activity therapeutic guidance')),
                ('coping_suggestions', models.JSONField(blank=True, default=list, help_text='Coping strategies for when stuck')),
                ('success_affirmations', models.JSONField(blank=True, default=list, help_text='Affirmations for after completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order_position', models.PositiveIntegerField(default=0)),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='learning.learningpath')),
            ],
            options={
                'verbose_name_plural': 'Micro Activities',
                'ordering': ['order_position', 'difficulty_level'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('retry_later', 'Retry Later')], db_index=True, default='not_started', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('successful_attempts', models.PositiveIntegerField(default=0)),
                ('submitted_code', models.TextField(blank=True)),
                ('code_output', models.TextField(blank=True)),
                ('errors', models.TextField(blank=True)),
                ('emotional_state_before', models.CharField(blank=True, max_length=50)),
                ('emotional_state_after', models.CharField(blank=True, max_length=50)),
                ('stress_level_before', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stress_level_after', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('confidence_before', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('confidence_after', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('self_assessment', models.IntegerField(blank=True, help_text='How do you feel about your attempt? (1=struggled, 5=proud)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reflection_notes', models.TextField(blank=True)),
                ('what_went_well', models.TextField(blank=True)),
                ('challenges_faced', models.TextField(blank=True)),
                ('coping_strategies_used', models.JSONField(blank=True, default=list)),
                ('code_quality_score', models.FloatField(blank=True, null=True)),
                ('efficiency_score', models.FloatField(blank=True, null=True)),
                ('breakthrough_notes', models.TextField(blank=True)),
                ('therapist_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.microactivity')),
            ],
            options={
                'verbose_name_plural': 'User Progress Records',
                'ordering': ['-updated_at'],
            },
        ),
    ]
