# Generated by Django 6.0 on 2025-12-12 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='microactivity',
            index=models.Index(fields=['difficulty_level', 'is_published'], name='learning_mi_difficu_40467d_idx'),
        ),
        migrations.AddIndex(
            model_name='microactivity',
            index=models.Index(fields=['therapeutic_focus', 'difficulty_level'], name='learning_mi_therape_3f4fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='learning_us_user_id_eebcd2_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['activity', 'status'], name='learning_us_activit_03a575_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'activity')},
        ),
    ]
