# Generated by Django 6.0 on 2025-12-12 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('tier', models.CharField(choices=[('gentle', '🌱 Gentle Start'), ('confident', '🌿 Building Confidence'), ('resilient', '🌳 Becoming Resilient'), ('master', '🏔️ Master of Self'), ('therapeutic', '🌟 Therapeutic Breakthrough')], max_length=20)),
                ('icon_name', models.CharField(default='star', max_length=50)),
                ('color', models.CharField(default='#FFD700', max_length=7)),
                ('requirement_type', models.CharField(choices=[('activities_completed', 'Complete Activities'), ('streak_days', 'Consecutive Days'), ('stress_reduction', 'Reduce Stress'), ('help_others', 'Help Others'), ('breakthrough', 'Therapeutic Breakthrough'), ('custom', 'Custom Criteria')], max_length=20)),
                ('requirement_value', models.IntegerField(default=1)),
                ('requirement_data', models.JSONField(blank=True, default=dict, help_text='Additional requirement data')),
                ('therapeutic_message', models.TextField(blank=True)),
                ('reflection_prompt', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CircleMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Circle Leader'), ('supporter', 'Active Supporter'), ('member', 'Member'), ('observer', 'Observer')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('support_given', models.PositiveIntegerField(default=0)),
                ('support_received', models.PositiveIntegerField(default=0)),
                ('notification_preferences', models.JSONField(blank=True, default=dict, help_text='Notification settings for circle')),
            ],
            options={
                'ordering': ['role', '-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='GentleInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('interaction_type', models.CharField(choices=[('encouragement', 'Words of Encouragement'), ('achievement', 'Achievement Share'), ('question', 'Gentle Question'), ('resource', 'Resource Share'), ('gratitude', 'Expression of Gratitude'), ('reflection', 'Learning Reflection'), ('support', 'Request Support')], db_index=True, default='encouragement', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public (Visible to all)'), ('community', 'Community Only'), ('anonymous', 'Anonymous'), ('private', 'Private to Recipient')], default='anonymous', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('allow_replies', models.BooleanField(default=True)),
                ('therapeutic_intent', models.TextField(blank=True, help_text='Intent behind the interaction')),
                ('expected_response_time', models.CharField(choices=[('no_response', 'No response needed'), ('whenever', 'Whenever convenient'), ('within_day', 'Within a day'), ('urgent', 'Needs attention')], default='whenever', max_length=20)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('is_moderated', models.BooleanField(default=False)),
                ('moderator_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Gentle Interactions',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_members', models.PositiveIntegerField(default=10)),
                ('is_public', models.BooleanField(default=False)),
                ('join_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('focus_areas', models.JSONField(blank=True, default=list, help_text='List of therapeutic focus areas')),
                ('community_guidelines', models.TextField(blank=True)),
                ('meeting_schedule', models.JSONField(blank=True, default=dict, help_text='Weekly meeting schedule')),
                ('total_interactions', models.PositiveIntegerField(default=0)),
                ('active_members', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-active_members', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Context about how achievement was earned')),
                ('shared_publicly', models.BooleanField(default=False)),
                ('reflection_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'User Achievements',
                'ordering': ['-earned_at'],
            },
        ),
    ]
