# Generated by Django 6.0 on 2025-12-19 13:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circlemembership',
            options={'ordering': ['role', 'joined_at']},
        ),
        migrations.AlterModelOptions(
            name='gentleinteraction',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-earned_at']},
        ),
        migrations.RemoveIndex(
            model_name='gentleinteraction',
            name='social_gent_sender__091c3b_idx',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='color',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='reflection_prompt',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='requirement_data',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='requirement_type',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='requirement_value',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='therapeutic_message',
        ),
        migrations.RemoveField(
            model_name='circlemembership',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='circlemembership',
            name='support_given',
        ),
        migrations.RemoveField(
            model_name='circlemembership',
            name='support_received',
        ),
        migrations.RemoveField(
            model_name='supportcircle',
            name='community_guidelines',
        ),
        migrations.RemoveField(
            model_name='supportcircle',
            name='meeting_schedule',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='context_data',
        ),
        migrations.AddField(
            model_name='achievement',
            name='criteria',
            field=models.JSONField(default=dict, help_text='Criteria for earning this achievement'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='total_earners',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circlemembership',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gentleinteraction',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gentleinteraction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.gentleinteraction'),
        ),
        migrations.AddField(
            model_name='gentleinteraction',
            name='therapeutic_impact_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='gentleinteraction',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportcircle',
            name='allow_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon_name',
            field=models.CharField(default='award', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=20),
        ),
        migrations.AlterField(
            model_name='circlemembership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='circlemembership',
            name='notification_preferences',
            field=models.JSONField(default=dict, help_text='Notification settings for this circle'),
        ),
        migrations.AlterField(
            model_name='circlemembership',
            name='role',
            field=models.CharField(choices=[('leader', 'Circle Leader'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='gentleinteraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gentleinteraction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gentleinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('encouragement', 'Encouragement'), ('question', 'Question'), ('share', 'Personal Share'), ('support', 'Request Support')], default='encouragement', max_length=20),
        ),
        migrations.AlterField(
            model_name='gentleinteraction',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gentleinteraction',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gentleinteraction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gentleinteraction',
            name='therapeutic_intent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gentleinteraction',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('community', 'Community Only'), ('circle', 'Circle Members Only'), ('private', 'Private'), ('anonymous', 'Anonymous')], default='community', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportcircle',
            name='active_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supportcircle',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_circles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportcircle',
            name='focus_areas',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supportcircle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supportcircle',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supportcircle',
            name='join_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supportcircle',
            name='max_members',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='supportcircle',
            name='total_interactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.achievement'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gentleinteraction',
            index=models.Index(fields=['visibility', 'created_at'], name='social_gent_visibil_b90a49_idx'),
        ),
        migrations.AddIndex(
            model_name='gentleinteraction',
            index=models.Index(fields=['sender', 'created_at'], name='social_gent_sender__63d0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcircle',
            index=models.Index(fields=['is_public', 'active_members'], name='social_supp_is_publ_635e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='supportcircle',
            index=models.Index(fields=['focus_areas'], name='social_supp_focus_a_6f3a30_idx'),
        ),
        migrations.RemoveField(
            model_name='gentleinteraction',
            name='expected_response_time',
        ),
        migrations.RemoveField(
            model_name='gentleinteraction',
            name='is_moderated',
        ),
        migrations.RemoveField(
            model_name='gentleinteraction',
            name='moderator_notes',
        ),
        migrations.RemoveField(
            model_name='gentleinteraction',
            name='replies_count',
        ),
        migrations.RemoveField(
            model_name='gentleinteraction',
            name='shares_count',
        ),
        migrations.RemoveField(
            model_name='gentleinteraction',
            name='uuid',
        ),
    ]
