# Generated by Django 6.0 on 2025-12-12 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='circlemembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gentleinteraction',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gentleinteraction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportcircle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_circles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circlemembership',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='social.supportcircle'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='social.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gentleinteraction',
            index=models.Index(fields=['interaction_type', 'created_at'], name='social_gent_interac_80e958_idx'),
        ),
        migrations.AddIndex(
            model_name='gentleinteraction',
            index=models.Index(fields=['sender', 'recipient', 'created_at'], name='social_gent_sender__091c3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='circlemembership',
            unique_together={('circle', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
