# Generated by Django 6.0 on 2025-12-12 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('strategy_type', models.CharField(choices=[('breathing', 'Breathing Exercise'), ('mindfulness', 'Mindfulness Practice'), ('cognitive', 'Cognitive Reframing'), ('physical', 'Physical Activity'), ('social', 'Social Connection'), ('creative', 'Creative Expression'), ('coding', 'Coding Integration'), ('planning', 'Planning/Organization')], max_length=20)),
                ('target_emotions', models.JSONField(default=list, help_text='List of emotions this strategy helps with')),
                ('estimated_minutes', models.PositiveIntegerField(default=5)),
                ('difficulty_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('coding_integration', models.BooleanField(default=False)),
                ('coding_language', models.CharField(blank=True, max_length=20)),
                ('coding_template', models.TextField(blank=True)),
                ('instructions', models.JSONField(default=list, help_text='Step-by-step instructions')),
                ('tips_for_success', models.TextField(blank=True)),
                ('common_challenges', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Coping Strategies',
                'ordering': ['strategy_type', 'difficulty_level'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_emotion', models.CharField(choices=[('anxious', '😰 Anxious/Worried'), ('overwhelmed', '😵 Overwhelmed/Stressed'), ('doubtful', '😔 Self-doubting/Insecure'), ('fatigued', '😴 Tired/Fatigued'), ('calm', '😌 Calm/Peaceful'), ('focused', '🎯 Focused/Concentrated'), ('hopeful', '🌟 Hopeful/Optimistic'), ('frustrated', '😤 Frustrated/Stuck'), ('excited', '🚀 Excited/Motivated'), ('neutral', '😐 Neutral/Balanced')], db_index=True, max_length=20)),
                ('secondary_emotions', models.JSONField(blank=True, default=list, help_text='List of secondary emotions')),
                ('intensity', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=3)),
                ('physical_symptoms', models.JSONField(blank=True, default=list, help_text='List of physical symptoms experienced')),
                ('trigger_description', models.TextField(blank=True)),
                ('context_tags', models.JSONField(blank=True, default=list, help_text='Tags describing context (work, learning, social, etc.)')),
                ('coping_strategies_used', models.JSONField(blank=True, default=list, help_text='Coping strategies attempted')),
                ('coping_effectiveness', models.IntegerField(blank=True, help_text='How effective were coping strategies (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True, help_text='Free-form reflection')),
                ('key_insight', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emotional Check-in',
                'verbose_name_plural': 'Emotional Check-ins',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
