# Generated by Django 6.0 on 2025-12-12 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionalcheckin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotional_checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emotionalcheckin',
            index=models.Index(fields=['user', '-created_at'], name='therapy_emo_user_id_a138a4_idx'),
        ),
        migrations.AddIndex(
            model_name='emotionalcheckin',
            index=models.Index(fields=['primary_emotion', 'created_at'], name='therapy_emo_primary_935b72_idx'),
        ),
    ]
